### PR TITLE
CSUB-1052 Community Gluwa Logo & Twitter Logo update

### PR DESCRIPTION
**Pull request by frankli-dev**
Screenshot 2024-02-15 at 8 01 27 AM

### CODE REVIEW

**Review by juanma1996 — APPROVED** [review]

**Review by atodorov — COMMENTED** [review]
@frankli-dev which ticket # is this ?

**Comment by frankli-dev** [comment]
> @frankli-dev which ticket # is this ?

No ticket.
https://gluwa.slack.com/archives/C05G20T3Y4S/p1707422079906999

**Comment by frankli-dev** [comment]
> @frankli-dev which ticket # is this ?

@atodorov I've created a Jira ticket for this and updated the PR title
https://gluwa.atlassian.net/browse/CSUB-1052

**Review by atodorov — APPROVED** [review]
Old:

image


New:
image

- Gluwa logo updated to be more readable b/c of background
- Twitter icon changed to X
-

**Pull request merged**
