### PR TITLE
CSUB-1118 The Revert Changes function is not working as expected but make Submit button disabled on Manage Nominations

### PR DESCRIPTION
**Pull request by frankli-dev**

### CODE REVIEW

**Comment by Dante9988** [comment]
@frankli-dev @atodorov I have went through the steps to repro and indeed Submit button is disabled when user initiates the Revert Changes function, but up until user adds another validator with Active, Random. Overall meets the expected result

https://github.com/gluwa/creditcoin3-staking-dashboard/assets/47313096/ca66a472-259b-4d75-877b-14e9338d76bd

**Review by Dante9988 — APPROVED** [review]
Approved based on previous comment

**Comment by Abas-Tim** [comment]
I performed the test steps too.

Issue is fixed now, revert button reverts as expected and submit button is greyed out after reverting 

https://github.com/gluwa/creditcoin3-staking-dashboard/assets/8209950/d8702381-c8a6-47be-b12a-9b224ce18ed8

**Review by Abas-Tim — APPROVED** [review]

**Comment by maishaf** [comment]
Revert function working as expected and Submit button is disabled after reverting 

https://github.com/gluwa/creditcoin3-staking-dashboard/assets/101668887/444966ea-100d-475c-9ebf-7f0bc5065217

**Review by maishaf — APPROVED** [review]

**Pull request merged**
