### PR TITLE
CSUB-1091: fix: Pool search bar invisible phrase and search criteria

### PR DESCRIPTION
**Pull request by frankli-dev**

### CODE REVIEW

**Review by atodorov — CHANGES_REQUESTED** [review]
Can you cherry-pick 5d3d0e7c395fc6fdbaa120b0018c6344b052e854 from https://github.com/gluwa/creditcoin3-staking-dashboard/pull/121 in order to satisfy the failing MegaLinter ?

**Review by atodorov — COMMENTED** [review]
This is how the filter looks like after shitching back & forth between tabs:

image

Functionality patch LGTM.

**Comment by DylanVerstraete** [comment]
Should it not either:

- Remove all search & selection (reset to default)
- Keep search + selection (all / active / locked / destroying)

Because, when you search for a pool and you have a (list) of inactive pools in the result, then you click on `Overview` and then come back to `All Pools`, selection `Active` is selected + search term is not reset resulting in an empty list of pools

**Comment by frankli-dev** [comment]
> Should it not either:
> 
> * Remove all search & selection (reset to default)
> * Keep search + selection (all / active / locked / destroying)
> 
> Because, when you search for a pool and you have a (list) of inactive pools in the result, then you click on `Overview` and then come back to `All Pools`, selection `Active` is selected + search term is not reset resulting in an empty list of pools

Thanks for your review.

I go with the first option. Removing all search & selection by default

**Comment by DylanVerstraete** [comment]
:+1: LGTM

**Review by atodorov — CHANGES_REQUESTED** [review]
Can you drop the first 2 commits - no need to add and then revert something we aren't using.

**Comment by frankli-dev** [comment]
> Can you drop the first 2 commits - no need to add and then revert something we aren't using.

We will do squash and merge. Those 2 commits won't be included in dev

**Comment by frankli-dev** [comment]
@atodorov Done

**Review by atodorov — APPROVED** [review]

**Pull request merged**
