### PR TITLE
CSUB-1019 Change the staking dashboard "waiting" label on the Validator page to Active + number

### PR DESCRIPTION
**Pull request by frankli-dev**

### CODE REVIEW

**Review by atodorov — COMMENTED** [review]
This is how it looks with only 1 validator - Alice:
Screenshot 2024-01-24 at 16-08-34 Creditcoin Staking Dashboard Creditcoin Staking (CTC)


This is how the dashboard looks with another validator added (1 era elapsed after adding it), which is still not in the list of active validators:
Screenshot 2024-01-24 at 16-09-02 Creditcoin Staking Dashboard Creditcoin Staking (CTC)

Screenshot 2024-01-24 at 16-09-25 Polkadot_Substrate Portal

**Review by atodorov — COMMENTED** [review]
Review & test round #2

:heavy_check_mark:  Validators are shown with the label "Active / X CTC":
01_only_Alice_shows_0_CTC

:heavy_check_mark: A second validator which has indicated their desire to validate, but is still waiting for the current era to elapse (and possible be selected in the validator set) is also shown as soon as they are chosen as part of the active validation set:
02_bob_is_still_waiting

:exclamation:  Clicking the "Clear" button doesn't seem to affect anything IMO. I have no idea how it is supposed to work and digging through the code to find that out seems like too much effort in the context of this ticket.

:heavy_check_mark: Having nominators articipate in the mix increases the amount of CTC shown as soon as these nominations become active. 

:heavy_multiplication_x: The CTC amount shown does not always sync properly and sometimes it shows "0 CTC". The easiest way to reproduce that is to refresh the page several times subsequently. It is probably unrelated to these actual changes.

**Comment by frankli-dev** [comment]
Also fixed the filter.

**Comment by atodorov** [comment]
> ❗ Clicking the "Clear" button doesn't seem to affect anything IMO. I have no idea how it is supposed to work and digging through the code to find that out seems like too much effort in the context of this ticket.

:green_circle: : Clicking the "Clear" button while Bob is still not in the active validator set now works for me. 

Screenshot 2024-01-26 at 19-13-47 Creditcoin Staking Dashboard Creditcoin Staking (CTC)


:x: ^^^ during the time in which Bob hasn't made it into the active validator set he is shown as "Active / 0 CTC", see screenshot.



> ❌ The CTC amount shown does not always sync properly and sometimes it shows "0 CTC". The easiest way to reproduce that is to refresh the page several times subsequently. It is probably unrelated to these actual changes.

:green_circle: this seems to have been fixed.

**Review by atodorov — DISMISSED** [review]
Looks like it needs a rebase to account for commits from #74.

**Review by nathanwhit — APPROVED** [review]

**Pull request merged**
