### PR TITLE
CSUB-959: Nomination pool members can't leave

### PR DESCRIPTION
**Pull request by frankli-dev**
Ticket:
https://gluwa.atlassian.net/browse/CSUB-959

Comment:
It's not an issue. We already have `withdrawUnbond` feature in `Members` tab. 
Current `Leave Pool` feature only does `unbondFunds`. So this PR corrects the label of the button.

### CODE REVIEW

**Review by atodorov — CHANGES_REQUESTED** [review]
The UI change looks good so wwe can probably merge it as-is.

However I don't think the underlying issue is resolved. My scenario is as follows:

1) Create a pool, 100_000 CTC initial deposit
2) N01 joins the pool with 10_000 CTC via Staking Dashboard (do not compound rewards)
3) N02 joins the poll with 10_00 CTC via Polkadot JS Apps (do not compound rewards)
4) After 1 era I initiate payouts to the pool
5) Both N01 and N02 can claim their chunk of rewards. That amounts to 1.38 CTC each. 
After witdrawing their rewards both accounts have roughly 1.82 CTC which seems correct (accounting for minor difference in fees). 

6) N01 initiates unbond from Staking Dashboard
7) N02 initiates unbond from Polkadot JS Apps

^^^ this happens at roughly the same time and events which are shown in explorrer look very similar

unbond_events_in Polkadot_Apps

Then however I check pool membership via Polkadot JS Apps and that's very different:
pool_members_stake_in_Polkadot_Apps

Notice how pool member stake is 0 for N02 but 9999 for N01 ! 

For some reason the amount of CTC we're waiting to be unlocked is the same, 0.0028 CTC. Not sure where this small number comes from.

What I've noticed is that when unbonding via Polkadot JS Apps you have to specify an amount and the default is for the maximum amount to be unbonded. 

@frankli-dev can you inspect Staking Dashboard if it also unbonds the maximum amount. That may be the root of the problem.


8) Additional information (I still think point 7) is the important one):

After both N01 and N02 initiate "withdraw unlocked", N02 is removed from the pool, while N01 is still a pool member
image 

In the block explorer I see `nominationPools.MemberRemoved` event for N02 but not for N01! (however that may be by design. I can't tell b/c Members tab is currently inaccessible due to missing Subscan API).

**Comment by atodorov** [comment]
The commit [fix: Correct bonded funds using Points](https://github.com/gluwa/creditcoin3-staking-dashboard/pull/37/commits/281e01ef1706796e8a54fe732b41ed6795518f18) seems to improve things quite a lot: 

0) Bonded funds are shown correctly on Staking Dashboard

bonded-funds-shown-correctly


1) 0 CTC shown for both pool members after both of them initiated unbond

0_CTC_shown_while_waiting_to_unclock_funds

2) After funds were unlocked both N01 and N02 were able to withdraw. In Staking Dashboard a new button appeared;

new_button_withdraw_unlocked

3) After both accounts withdrew their funds then were both removed from the pool. I saw `nominationPools.MemberRemoved` events for both and they are no longer shown as pool members. 


Outlining a few smaller issues b/c I think they can be improved similarly to your last commit:

1) The new button from 2) is called "Withdraw Unlocked" which on Polkadot JS Apps the menu is called "Withdraw Unbonded"
2) The numbers shown in the waiting modal as well as after clicking on the "Withdraw Unlocked" button seems incorrect
I am waiting to unbond 10_000 CTC, not some small amount. Same when withdrawing.  Note that Polakdot JS Apps is consistent with Staking Dashboard here but I think that both of them are wrong:

popup-seems-incorrect-though

popup-similar-to-polkadot-but-still-may-be-incorrect


3) FYI after withdrawing the 10_000 balance for both N01 and N02 is still off. They have 6 CTC which accounts for rewards and fees, but the rest 10k is missing. That I think is the same behavior as CSUB-963, so I'll post it there for further testing!

image

**Review by atodorov — CHANGES_REQUESTED** [review]
I'm not sure this commit is intentional: [Revert "fix: Correct bonded funds using Points"](https://github.com/gluwa/creditcoin3-staking-dashboard/pull/37/commits/190aa69689972290d2009c6f4fc4e9bf2aa2dc6a)

Need to discuss this before we can go ahead and merge this change!

**Comment by frankli-dev** [comment]
> I'm not sure this commit is intentional: [Revert "fix: Correct bonded funds using Points"](https://github.com/gluwa/creditcoin3-staking-dashboard/pull/37/commits/190aa69689972290d2009c6f4fc4e9bf2aa2dc6a)
> 
> Need to discuss this before we can go ahead and merge this change!

Yes, it is intentional. It should be fixed correctly on blockchain not on UI. 
The issue should be fixed here, https://github.com/gluwa/creditcoin3/pull/131

**Review by nathanwhit — APPROVED** [review]

**Comment by frankli-dev** [comment]
@atodorov Can we merge this?

**Comment by atodorov** [comment]
> @atodorov Can we merge this?

FTR the scope of this PR has currently changed and it is about renaming the "Leave" button to "Unbond Funds" when a user is a member of a nomnation pool!

IIRC it was up for discussion whether this button should be renamed or not. I don't think there is a decision on this yet!

While personally I agree that it may be confusing my preference is to keep it the same as Polkadot Staking Dashboard upstream. That is not to merge this PR. However it needs a decision from a product stakeholder!

**Review by atodorov — APPROVED** [review]
Merging after product has decided that we'd like to rename this button!

**Pull request merged**
